"""Byte-identical gate for the aweb-naapp toolkit refactor.

library's surfaces are now generated by the shared toolkit. These goldens are the
exact output captured before the refactor (commit d082499); the rendered pages
must match them byte for byte so the live surface is unchanged.
"""

from __future__ import annotations

from pathlib import Path

from library.surfaces import aweb_css, llms_txt, render_landing_page, render_reference_page

_GOLDEN = Path(__file__).resolve().parent / "golden"
_ORIGIN = "https://library.aweb.ai"


def _golden(name: str) -> str:
    return (_GOLDEN / name).read_text(encoding="utf-8")


def test_landing_is_byte_identical() -> None:
    assert render_landing_page(public_origin=_ORIGIN) == _golden("landing.html")


def test_reference_is_byte_identical() -> None:
    assert render_reference_page(public_origin=_ORIGIN) == _golden("reference.html")


def test_llms_txt_is_byte_identical() -> None:
    assert llms_txt(public_origin=_ORIGIN) == _golden("llms.txt")


def test_aweb_css_is_byte_identical() -> None:
    assert aweb_css() == _golden("aweb.css")
