#!/usr/bin/env python3
"""Update AC's reviewed aweb source identity and exact Python dependency lock.

This is the `ac-pin` pointer effect only. It clones AC, prepares one coherent
source-pointer commit, runs AC's own release-model/lock/immutability checks,
and pushes that commit. It never deploys AC, runs migrations, reads production
credentials, or crosses AC's separate human-approved release gate.

The PointerLane protocol is:

    intent --component ac-pin --updates '{...}'
    apply  --component ac-pin --updates '{...}'
    read   --component ac-pin

`server` is a complete {version, git_ref, git_sha} identity. `awid-pypi` is the
published version. Lockfiles are always regenerated by uv with exact package
constraints; they are never edited line-by-line.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import NoReturn
from urllib.parse import urlparse

PIN_FILE = "release-pin.toml"
PYPROJECT_FILE = "backend/pyproject.toml"
LOCK_FILE = "backend/uv.lock"
DEFAULT_REMOTE = "git@github.com:awebai/ac.git"
DEFAULT_AWEB_REMOTE = "git@github.com:awebai/aweb.git"
PYPI_INDEX = "https://pypi.org/simple"
GIT = "/usr/bin/git"
SERVER_IDENTITY_FIELDS = frozenset({"version", "git_ref", "git_sha"})
VERSION_RE = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+")
SHA_RE = re.compile(r"[0-9a-f]{40}")
HASH_RE = re.compile(r"sha256:[0-9a-f]{64}")


def fail(message: str) -> NoReturn:
    raise SystemExit(message)


def git_env() -> dict[str, str]:
    """Use fixed Git policy; ambient config must not redirect a push."""
    return {
        "PATH": "/usr/bin:/bin",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_CONFIG_SYSTEM": "/dev/null",
        "GIT_CONFIG_COUNT": "0",
        "GIT_TERMINAL_PROMPT": "0",
        "GIT_ALLOW_PROTOCOL": "ssh:https:file",
        "HOME": os.environ.get("HOME", "/tmp"),
        "SSH_AUTH_SOCK": os.environ.get("SSH_AUTH_SOCK", ""),
        "GIT_AUTHOR_NAME": "aweb release driver",
        "GIT_AUTHOR_EMAIL": "release@aweb.ai",
        "GIT_COMMITTER_NAME": "aweb release driver",
        "GIT_COMMITTER_EMAIL": "release@aweb.ai",
    }


def check_env() -> dict[str, str]:
    """The contract checks need tools/cache only, never production secrets."""
    keep = ("HOME", "TMPDIR", "LANG", "LC_ALL", "UV_CACHE_DIR")
    env = {key: os.environ[key] for key in keep if key in os.environ}
    env["PATH"] = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
    return env


def run(command: list[str], *, cwd: Path, env=None) -> str:
    result = subprocess.run(
        command, cwd=str(cwd), env=env, capture_output=True, text=True
    )
    if result.returncode != 0:
        rendered = " ".join(command)
        detail = result.stderr.strip() or result.stdout.strip()
        fail(f"{rendered} failed: {detail}")
    return result.stdout


def git(*args: str, cwd: Path) -> str:
    return run([GIT, *args], cwd=cwd, env=git_env())


def expected_remote() -> str:
    return os.environ.get("AC_REMOTE", DEFAULT_REMOTE)


def aweb_remote() -> str:
    return os.environ.get("AWEB_REMOTE", DEFAULT_AWEB_REMOTE)


def canonical(remote: str) -> str:
    value = remote.strip()
    for prefix in ("git@github.com:", "https://github.com/", "ssh://git@github.com/"):
        if value.startswith(prefix):
            value = "github.com/" + value[len(prefix):]
            break
    return value[:-4] if value.endswith(".git") else value


def require_expected(expected: str | None) -> str:
    remote = expected_remote()
    if not expected:
        fail(
            "refusing to act without --expect-repository: the release must name "
            "the repository it intends to mutate"
        )
    if canonical(expected) != canonical(remote):
        fail(f"refusing to act on {remote}: the release expects {expected}")
    return remote


def verify_origin(checkout: Path, expected: str, when: str) -> None:
    actual = git("remote", "get-url", "origin", cwd=checkout).strip()
    if canonical(actual) != canonical(expected):
        fail(f"refusing: {when} the checkout's origin is {actual}, not {expected}")


def clone(into: Path, remote: str, name: str) -> Path:
    checkout = into / name
    git("clone", "--depth", "1", remote, str(checkout), cwd=into)
    verify_origin(checkout, remote, "after cloning")
    return checkout


def read_pins(checkout: Path) -> dict:
    try:
        pin = tomllib.loads((checkout / PIN_FILE).read_text())
        aweb = pin["aweb"]
        server = {field: aweb[field] for field in sorted(SERVER_IDENTITY_FIELDS)}
        lock = tomllib.loads((checkout / LOCK_FILE).read_text())
        awid = next(
            package["version"]
            for package in lock["package"]
            if package.get("name") == "awid-service"
        )
    except (FileNotFoundError, KeyError, StopIteration, tomllib.TOMLDecodeError) as exc:
        fail(f"AC source-pointer state is malformed: {exc}")
    return {"server": server, "awid-pypi": awid}


def validate_server_identity(value) -> dict[str, str]:
    if not isinstance(value, dict) or set(value) != SERVER_IDENTITY_FIELDS:
        fail(
            "server update must contain exactly version, git_ref and git_sha; "
            "partial source identities are refused"
        )
    identity = {key: value[key] for key in SERVER_IDENTITY_FIELDS}
    if not isinstance(identity["version"], str) or not VERSION_RE.fullmatch(
        identity["version"]
    ):
        fail(f"server version is not strict X.Y.Z: {identity['version']!r}")
    expected_ref = f"server-v{identity['version']}"
    if identity["git_ref"] != expected_ref:
        fail(
            f"server git_ref {identity['git_ref']!r} does not match version; "
            f"expected {expected_ref!r}"
        )
    if not isinstance(identity["git_sha"], str) or not SHA_RE.fullmatch(
        identity["git_sha"]
    ):
        fail(f"server git_sha must be full 40-hex, got {identity['git_sha']!r}")
    return identity


def validate_updates(updates) -> dict:
    if not isinstance(updates, dict) or not updates:
        fail("ac-pin update must name server and/or awid-pypi")
    unknown = sorted(set(updates) - {"server", "awid-pypi"})
    if unknown:
        fail(f"ac-pin holds no pin for: {unknown}")
    normalized = {}
    if "server" in updates:
        normalized["server"] = validate_server_identity(updates["server"])
    if "awid-pypi" in updates:
        version = updates["awid-pypi"]
        if not isinstance(version, str) or not VERSION_RE.fullmatch(version):
            fail(f"awid-pypi version is not strict X.Y.Z: {version!r}")
        normalized["awid-pypi"] = version
    return normalized


def tagged_sha(remote: str, git_ref: str, *, cwd: Path) -> str:
    output = git(
        "ls-remote", remote, f"refs/tags/{git_ref}", f"refs/tags/{git_ref}^{{}}",
        cwd=cwd,
    )
    refs = {}
    for line in output.splitlines():
        sha, ref = line.split(maxsplit=1)
        refs[ref] = sha
    return refs.get(f"refs/tags/{git_ref}^{{}}") or refs.get(
        f"refs/tags/{git_ref}", ""
    )


def checkout_aweb(
    into: Path, identity: dict[str, str], *, require_published_tag: bool
) -> Path:
    remote = aweb_remote()
    if require_published_tag:
        tag_sha = tagged_sha(remote, identity["git_ref"], cwd=into)
        if tag_sha != identity["git_sha"]:
            fail(
                f"aweb tag {identity['git_ref']} resolves to "
                f"{tag_sha or 'absent'}, not {identity['git_sha']}"
            )
    checkout = clone(into, remote, "aweb")
    git("fetch", "--depth", "1", "origin", identity["git_sha"], cwd=checkout)
    if require_published_tag:
        git(
            "fetch", "--depth", "1", "origin",
            f"refs/tags/{identity['git_ref']}", cwd=checkout,
        )
    git("checkout", "--detach", identity["git_sha"], cwd=checkout)
    actual = git("rev-parse", "HEAD", cwd=checkout).strip()
    if actual != identity["git_sha"]:
        fail(f"aweb checkout is {actual}, not {identity['git_sha']}")
    try:
        version = tomllib.loads(
            (checkout / "server" / "pyproject.toml").read_text()
        )["project"]["version"]
    except (FileNotFoundError, KeyError, tomllib.TOMLDecodeError) as exc:
        fail(f"cannot read aweb server version at {identity['git_sha']}: {exc}")
    if version != identity["version"]:
        fail(
            f"aweb source {identity['git_sha']} declares server {version}, "
            f"not {identity['version']}"
        )
    return checkout


def replace_dependency(path: Path, package: str, version: str) -> None:
    text = path.read_text()
    updated, count = re.subn(
        rf'"{re.escape(package)}>=[^"]+"', f'"{package}>={version}"', text,
        count=1,
    )
    if count != 1:
        fail(f"{path} does not carry exactly one {package} dependency floor")
    path.write_text(updated)


def replace_pin_identity(path: Path, identity: dict[str, str]) -> None:
    text = path.read_text()
    for field in ("version", "git_sha", "git_ref"):
        pattern = rf'(?ms)(^\[aweb\].*?^{field}\s*=\s*")[^"]*(")'
        text, count = re.subn(
            pattern,
            lambda match, value=identity[field]: match.group(1) + value + match.group(2),
            text,
            count=1,
        )
        if count != 1:
            fail(f"{PIN_FILE} [aweb] does not carry exactly one {field}")
    path.write_text(text)


def uv_binary() -> str:
    executable = shutil.which("uv", path=check_env()["PATH"])
    if not executable:
        fail("uv is required to regenerate AC's exact lock")
    return executable


def regenerate_lock(
    checkout: Path, *, server_version: str, awid_version: str
) -> None:
    command = [uv_binary(), "lock", "--no-config"]
    test_index = os.environ.get("AC_PIN_TEST_INDEX")
    if test_index:
        if canonical(expected_remote()) == canonical(DEFAULT_REMOTE):
            fail("test package index is refused for the production AC remote")
        command += ["--index", test_index]
    command += [
        "--default-index", PYPI_INDEX,
        "--upgrade-package", f"aweb=={server_version}",
        "--upgrade-package", f"awid-service=={awid_version}",
    ]
    run(command, cwd=checkout / "backend", env=check_env())


def verify_lock_package(checkout: Path, name: str, version: str) -> None:
    lock = tomllib.loads((checkout / LOCK_FILE).read_text())
    try:
        package = next(item for item in lock["package"] if item.get("name") == name)
    except StopIteration:
        fail(f"regenerated lock carries no {name}")
    if package.get("version") != version:
        fail(f"regenerated lock has {name} {package.get('version')}, not {version}")
    normalized = name.replace("-", "_")
    filename_identity = f"{normalized}-{version}"
    artifacts = [package.get("sdist"), *(package.get("wheels") or [])]
    if len(artifacts) < 2 or any(not isinstance(item, dict) for item in artifacts):
        fail(f"regenerated lock lacks complete sdist/wheel artifacts for {name} {version}")
    for artifact in artifacts:
        url = artifact.get("url")
        digest = artifact.get("hash")
        filename = Path(urlparse(url).path).name if isinstance(url, str) else ""
        if filename_identity not in filename or not isinstance(digest, str) \
           or not HASH_RE.fullmatch(digest):
            fail(
                f"regenerated lock artifact for {name} {version} is incoherent: "
                f"url={url!r}, hash={digest!r}"
            )


def make_binary() -> str:
    executable = shutil.which("make", path=check_env()["PATH"])
    if not executable:
        fail("make is required to run AC's release-model check")
    return executable


def require_ac_contract_surfaces(checkout: Path) -> None:
    make_binary()
    makefile = checkout / "Makefile"
    try:
        make_text = makefile.read_text()
    except OSError as exc:
        fail(f"AC checkout lacks readable Makefile: {exc}")
    if not re.search(r"(?m)^release-verify-model:\s*$", make_text):
        fail("AC Makefile lacks the release-verify-model target")
    required = (
        ("scripts/check_release_model.py", False),
        ("scripts/check_release_overlay.py", False),
        ("scripts/check-aapj-e2e-contract.sh", True),
        ("backend/scripts/migration_manifest.py", False),
    )
    for relative, executable in required:
        path = checkout / relative
        if not path.is_file():
            fail(f"AC checkout lacks required contract check {relative}")
        if executable and not os.access(path, os.X_OK):
            fail(f"AC contract check is not executable: {relative}")


def run_ac_checks(checkout: Path) -> None:
    require_ac_contract_surfaces(checkout)
    run([make_binary(), "release-verify-model"], cwd=checkout, env=check_env())
    run(
        [uv_binary(), "lock", "--check", "--no-config"],
        cwd=checkout / "backend", env=check_env(),
    )
    run(
        [sys.executable, "scripts/migration_manifest.py", "--verify"],
        cwd=checkout / "backend", env=check_env(),
    )


def prepare_intent(checkout: Path, updates: dict) -> None:
    """Check only facts available before source publication.

    Candidate source commits exist before their release tags and registry
    artifacts. Intent validates their exact source version and AC's writable
    contract, but apply alone requires the future tag/artifacts and runs the
    resulting AC gates.
    """
    current = read_pins(checkout)
    server = updates.get("server", current["server"])
    checkout_aweb(checkout.parent, server, require_published_tag=False)
    if "server" in updates:
        replace_pin_identity(checkout / PIN_FILE, server)
        replace_dependency(checkout / PYPROJECT_FILE, "aweb", server["version"])
    if "awid-pypi" in updates:
        replace_dependency(
            checkout / PYPROJECT_FILE, "awid-service", updates["awid-pypi"]
        )
    uv_binary()
    require_ac_contract_surfaces(checkout)


def prepare_updates(checkout: Path, updates: dict) -> list[str]:
    current = read_pins(checkout)
    server = updates.get("server", current["server"])
    checkout_aweb(checkout.parent, server, require_published_tag=True)

    touched = set()
    if "server" in updates:
        replace_pin_identity(checkout / PIN_FILE, server)
        replace_dependency(
            checkout / PYPROJECT_FILE, "aweb", server["version"]
        )
        touched.update({PIN_FILE, PYPROJECT_FILE, LOCK_FILE})
    if "awid-pypi" in updates:
        replace_dependency(
            checkout / PYPROJECT_FILE, "awid-service", updates["awid-pypi"]
        )
        touched.update({PYPROJECT_FILE, LOCK_FILE})
    expected_awid = updates.get("awid-pypi", current["awid-pypi"])
    regenerate_lock(
        checkout,
        server_version=server["version"],
        awid_version=expected_awid,
    )

    verify_lock_package(checkout, "aweb", server["version"])
    verify_lock_package(checkout, "awid-service", expected_awid)
    run_ac_checks(checkout)

    changed = {
        line[3:] for line in git("status", "--porcelain", cwd=checkout).splitlines()
        if len(line) > 3
    }
    if not changed.issubset(touched):
        fail(
            "AC update changed files outside its pointer contract: "
            f"{sorted(changed - touched)}"
        )
    return sorted(touched)


def apply_updates(checkout: Path, updates: dict, remote: str) -> list[str]:
    touched = prepare_updates(checkout, updates)
    if os.environ.get("AC_PIN_TEST_CRASH_AFTER_CHECKS") == "1":
        if canonical(remote) == canonical(DEFAULT_REMOTE):
            fail("test crash injection is refused for the production AC remote")
        fail("injected crash after checks and before commit/push")

    for path in touched:
        git("add", path, cwd=checkout)
    if not git("status", "--porcelain", cwd=checkout).strip():
        return touched
    summary = ", ".join(f"{key} {value}" for key, value in sorted(updates.items()))
    git("commit", "-m", f"Pin {summary}", cwd=checkout)
    verify_origin(checkout, remote, "before pushing")
    git("push", "origin", "HEAD:main", cwd=checkout)
    verify_origin(checkout, remote, "after pushing")
    return touched


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("operation", choices=("intent", "apply", "read"))
    parser.add_argument("--component", required=True)
    parser.add_argument("--expect-repository")
    parser.add_argument("--updates")
    args = parser.parse_args(argv)
    if args.component != "ac-pin":
        fail(f"adapter serves ac-pin, not {args.component}")
    remote = require_expected(args.expect_repository)
    updates = validate_updates(json.loads(args.updates)) if args.updates else None

    with tempfile.TemporaryDirectory() as tmp:
        checkout = clone(Path(tmp), remote, "ac")
        if args.operation == "read":
            print(json.dumps({"advertised": read_pins(checkout)}, sort_keys=True))
            return 0
        if updates is None:
            fail(f"{args.operation} requires --updates")
        if args.operation == "intent":
            prepare_intent(checkout, updates)
            print(json.dumps({"advertised": updates}, sort_keys=True))
        else:
            apply_updates(checkout, updates, remote)
            print(json.dumps({"applied": updates}, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
